# Generated by Django 3.0 on 2021-02-23 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210218_1647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mango',
        ),
    ]
